name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          pip install pytailwindcss
          tailwindcss -i tailwind.styles.css -o src/public/styles.css --minify

      - name: Setup
        run: |
          curl -fsSL https://deta.space/assets/space-cli.sh | sh
          echo ${{ secrets.DETA_TOKEN }} | ~/.detaspace/bin/space login --with-token

      - name: Deploy
        run: |
          ~/.detaspace/bin/space new
          ~/.detaspace/bin/space push
